In [16]:
import pandas as pd
from io import StringIO
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df=pd.read_json(StringIO(Data))

In [ ]:
df

In [ ]:
df.to_json()

In [ ]:
df.to_json(orient='index')

In [ ]:
df.to_json(orient='records')

In [ ]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [ ]:
df.head()

In [ ]:
df.to_csv("wine.csv")

In [ ]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df=pd.read_html(url)

In [ ]:
df[0]

In [ ]:
url="https://en.wikipedia.org/wiki/Mobile_country_code"
pd.read_html(url,match="Country",header=0)[0]

In [20]:
df_excel=pd.read_excel('data.xlsx')
df_excel

    Name  Age
0  Krish   32
1   Jack   34
2   John   31

In [21]:
df_excel.to_pickle('df_excel')

In [22]:
pd.read_pickle('df_excel')

    Name  Age
0  Krish   32
1   Jack   34
2   John   31